# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: "ruby"
script: "bundle exec rake --trace"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-head
  - rbx-2
notifications:
  irc: "irc.freenode.org#savon"

matrix:
  allow_failures:
    - rvm: jruby-head
